name: Build and Deploy to Github Pages
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build Vue
        run: npm install && npm run build-only

      - name: Upload to Github Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target-branch: gh-pages
          build_dir: dist/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}